# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Node.js LTS (Alpine) image
FROM node:18-alpine AS build

# Install build dependencies
WORKDIR /app

# Copy package.json and lockfile
COPY package.json .
COPY bun.lock .

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy source and build
COPY tsconfig.json .
COPY src ./src
RUN npm run build

# Production image
FROM node:18-alpine
WORKDIR /app

# Copy built artifacts and production dependencies
COPY package.json .
COPY --from=build /app/build ./build

# Install only production dependencies
RUN npm install --production --ignore-scripts

# Ensure binary permission
RUN chmod +x build/index.js

# Add the binary to PATH via npm bin link
RUN npm link

# Default entrypoint
ENTRYPOINT ["frontend-review-mcp"]

# By default, the server runs with args from Smithery config
CMD []
